version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      WATCHMYSIX_DATA_DIR: /data
    volumes:
      - backend-data:/data

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://backend:8000
    depends_on:
      - backend

volumes:
  backend-data:
